[platformio]
default_envs = esp32dev
src_dir = ESP_Code

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
monitor_speed = 500000
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3
    tzapu/WiFiManager
    https://github.com/TridentTD/TridentTD_EasyFreeRTOS32.git
build_flags =
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DCAPTIVE_PORTAL
    -DWEB_DASHBOARD
build_src_flags =
    -include PlatformIOCompat.h
